# Study info
study_name: NCIL_EEG_template
task: bci
data_type: eeg
# Ethics board name and protocol ID
reb_info: Dalhousie SSHREB 20xx-xxxx
# add additional project team member names
authors:
  - Aaron J. Newman
# Specify source of study funding ('NSERC', 'SSHRC', etc.)
funding: None

# EEG recording details
amp_mfr: BrainVision
amp_model: actiCHamp
sw_filt:
  - Highpass filter:
      - half-amplitude cutoff (Hz): .01
  - Lowpass filter:
      - half-amplitude cutoff (Hz): 130
hw_filt:
  - Anti-aliasing filter:
    - half-amplitude cutoff (Hz): 130
    - rolloff: 3dB per octave # obtain from amplifier/recording software manual
eeg_ref: average
eeg_ground: FCz
cap_mfr: BrainVision
cap_model: ActiCap
eog:
  - HEOG
  - VEOG
montage_fname: standard_1005

# If we want 32 ch data + EOG with OpenVibe we need to record 66 channels, then drop ch 33-64
# Otherwise, leave blank 
drop_ch: AF7, AF3, AF4, AF8, F5, F1, F2, F6, FT9, FT7, FC3, FC4, FT8, FT10, C5, C1, C2, C6, TP7, CP3, CPz, CP4, TP8, P5, P1, P2, P6, PO7, PO3, POz, PO4, PO8

# Lab Info - should be the same for all studies
line_freq: 60
instn: Dalhousie University
instn_addr: Halifax, NS, Canada
instn_dept: NeuroCognitive Imaging Lab, Department of Psychology & Neuroscience
license: BSD 3-clause

