# Study info
study_name: NCIL_EEG_template
task: bci
data_type: eeg
# Ethics board name and protocol ID
reb_info: Dalhousie SSHREB 20xx-xxxx
# add additional project team member names
authors:
  - Aaron J. Newman
# Specify source of study funding ('NSERC', 'SSHRC', etc.)
funding: None

# EEG recording details
amp_mfr: BrainVision  # TMSi
amp_model: actiCHamp  # RefA8
eeg_extn: vhdr        # raw, set

sw_filt:
  - Highpass filter:
      - half-amplitude cutoff (Hz): .01
  - Lowpass filter:
      - half-amplitude cutoff (Hz): 130
hw_filt:
  - Anti-aliasing filter:
    - half-amplitude cutoff (Hz): 130
    - rolloff: 3dB per octave # obtain from amplifier/recording software manual
eeg_ref: average
eeg_ground: FCz
cap_mfr: BrainVision
cap_model: ActiCap
eog:
  - HEOG
  - VEOG
montage_fname: standard_1005

# If we want 32 ch data + EOG with OpenVibe we need to record 66 channels, then drop ch 33-64
# Otherwise, leave blank 
drop_ch: AF7, AF3, AF4, AF8, F5, F1, F2, F6, FT9, FT7, FC3, FC4, FT8, FT10, C5, C1, C2, C6, TP7, CP3, CPz, CP4, TP8, P5, P1, P2, P6, PO7, PO3, POz, PO4, PO8

# Lab Info - should be the same for all studies
line_freq: 60
instn: Dalhousie University
instn_addr: Halifax, NS, Canada
instn_dept: NeuroCognitive Imaging Lab, Department of Psychology & Neuroscience
license: BSD 3-clause


# ERP preprocessing parameters
preprocessing_settings:
  filter:
    - l_freq: 0.1
    - l_freq_ica: 1.
    - h_freq: 30.0
    - filter_picks:
      - eeg
      - eog

  # for multithreaded operations
  n_jobs: 5

  ica:
    - ica_random_state: 42  # seed so ICA is reproducable each time it's run
    - n_components: .95     # Specify n_components as a decimal to set % explained variance
    - tstep: 1.0
    - ica_zthresh: 2
    - ica_zstep: .1
    - n_max_eog: 2

  # note that a blank value is mapped to None type in Python
  # In contrast, putting 'None' in this file results in a string in Python (not what you want)
  epoch:
    - tmin: -0.500  # start of each epoch (in sec)
    - tmax:  1.250  # end of each epoch (in sec)
    # baseline should be left blank for preprocessing
    - baseline:
    - detrend: 1
    - reject:
    - flat:
    - rereference: average
    # - conditions: 
    #   - 'pic_onset'
    #   - 'match'
    #   - 'mismatch'
    # - contrasts:
      # - N400: ['mismatch', 'match']


### Analysis settings
analysis_settings:
  - t_min: -0.500
  - t_max:  1.00
  - baseline: (None, 0)
  - outlier_thresh: 2.

rois: 
  - vertex:
    - C3, Cz, C4, CP1, CPz, CP2, Pz
    
components:
  n400:
    t_min: -0.200
    t_max: 1.00
    baseline: (-0.200, 0)
    reference: TP9, TP10
    rois:
      - vertex
    peak_lat: 0.400
    tw_width: .200
    tw_range: 
        - .250
        - .550
    component_meas: meana
  
  
classification:
  - test_size: .20
  - random_state: 42 
